##### all packages and libraries ####
#install.packages("nortsTest")
#install.packages("urca")
#install.packages("aTSA")
#install.packages("strucchange")
#install.packages("MTS")
#install.packages("vtable")
#install.packages("ROI.plugin.glpk")
#install.packages("PortfolioAnalytics")
#install.packages("ROI")
#install.packages("optimx")
#install.packages("ROI.plugin.optimx")
#install.packages("ROI.plugin.quadprog")
#install.packages("QuantPsyc")
#install.packages("energy")
#install.packages("gt")
#install.packages('openxlsx')

###### libraries #######
library(data.table)
library(xts)
library(ROI.plugin.optimx)
library(ROI.plugin.quadprog)
library(PortfolioAnalytics)
library(PerformanceAnalytics)
library(ROI.plugin.glpk)
library(astsa)
library(corrplot)
library(tseries)
library(urca)
library(rugarch)
library(nortsTest)
library(strucchange)
library(MTS)
library(vtable)
library(lmtest)
library(forecast)
library(QuantPsyc)
library(energy)
library(gt)
library(openxlsx)

